apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "quay"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "pass"
  PGDATA: "/var/lib/postgresql/pgdata"
#  POSTGRES_PORT: "5432"
