apiVersion: v1
kind: Service
metadata:
  name: quay
  labels:
    app: quay
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30080
    - port: 8443
      name: https
      targetPort: 8443
      nodePort: 30443
  selector:
    app: quay
