# sudo podman run --rm -it --name quay_config -p 8443:8443 quay.io/projectquay/quay config secret
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay
  labels:
    app: quay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quay
  template:
    metadata:
      labels:
        app: quay
    spec:
      containers:
        - name: quay
          image: quay.io/projectquay/quay
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
#          envFrom:
#            - configMapRef:
#                name: quay-config
          volumeMounts:
            - name: quay-persistent-storage
              mountPath: /datastorage
            - name: quay-config-storage
              mountPath: /quay-registry/conf/stack/
      volumes:
        - name: quay-persistent-storage
          persistentVolumeClaim:
            claimName: quay-storage-pvc
        - name: quay-config-storage
          persistentVolumeClaim:
            claimName: quay-config-pvc
